name: flutter_my_templates
repository: https://github.com/FirebaseExtended/flutterfire

packages:
  - packages/**
  - "tests/*"

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # # Only allow versioning to happen on main branch.
    # branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
scripts:
  lint:all:
    run: melos run analyze
    description: Run all static analysis checks.

  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
  install:
    run: |
      melos exec -- \
        "flutter pub get"
    description: Run install.
    select-package:
      scope: "flutter_bloc_navigator_2"

  web:
    run: |
      melos exec -- \
        "flutter run -d web-server"
    description: Run web-server for template flutter_bloc_navigator_2.
    select-package:
      scope: "flutter_bloc_navigator_2"