include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [
      lib/src/**.g.dart,
      lib/src/common/configs/dependency_injection/injection.config.dart,
      lib/src/localization/dart_files/**.dart,
  ]

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    avoid_dynamic_calls: false